  - name: Create Alert Syslog object to forward all events to external syslog server
    avi_alertsyslogconfig:
      controller: ''
      name: Roberts-syslog
      password: ''
      syslog_servers:
      - syslog_server: 10.10.0.100
        syslog_server_port: 514
        udp: true
      tenant_ref: admin
      username: ''
