- name: configure top level configuration
  aruba_config:
    lines: hostname {{ inventory_hostname }}

- name: diff the running-config against a provided config
  aruba_config:
    diff_against: intended
    intended: "{{ lookup('file', 'master.cfg') }}"

- name: configure interface settings
  aruba_config:
    lines:
      - description test interface
      - ip access-group 1 in
    parents: interface gigabitethernet 0/0/0

- name: load new acl into device
  aruba_config:
    lines:
      - permit host 10.10.10.10
      - ipv6 permit host fda9:97d6:32a3:3e59::3333
    parents: ip access-list standard 1
    before: no ip access-list standard 1
    match: exact
