---
- name: Create a Snapshot
  aci_config_snapshot:
    hostname: apic
    username: admin
    password: SomeSecretPassword
    state: present
    export_policy: config_backup

- name: Query Existing Snapshots
  aci_config_snapshot:
    hostname: apic
    username: admin
    password: SomeSecretPassword
    state: query
    export_policy: config_backup

- name: Compare Snapshot Files
  aci_config_rollback:
    hostname: apic
    username: admin
    password: SomeSecretPassword
    state: preview
    export_policy: config_backup
    snapshot: 'run-2017-08-28T06-24-01'
    compare_export_policy: config_backup
    compare_snapshot: 'run-2017-08-27T23-43-56'

- name: Rollback Configuration
  aci_config_rollback:
    hostname: apic
    username: admin
    password: SomeSecretPassword
    state: rollback
    import_policy: rollback_config
    export_policy: config_backup
    snapshot: 'run-2017-08-28T06-24-01'

- name: Rollback Configuration
  aci_config_rollback:
    hostname: apic
    username: admin
    password: SomeSecretPassword
    state: rollback
    import_policy: rollback_config
    export_policy: config_backup
    snapshot: 'run-2017-08-28T06-24-01'
    description: 'Rollback 8-27 changes'
    import_mode: atomic
    import_type: replace
    fail_on_decrypt: yes
